### ISSUE TITLE
AbbVeyor builds fails

### ISSUE THREAD

**Issue by ningod** [eirslett/frontend-maven-plugin#554]
**Bug Report**

AbbVeyor  builds on pull request fails, due to configuration problems on the server side ( there is no appveyor.yml file on github ).
Please change configuration or add to appveyor.yml file to repo to fix the problem.

**Comment by eirslett** [comment]
It has worked fine so far. It's not configured with an appveyor.yml, it's configured separately on the project configuration on appveyor.com. There's probably an unrelated reason why the build fails.

**Comment by ningod** [comment]
I suppose something is changed last days, maven installation by choco goes in error. try to use something like this:
```yml
version: '{build}'
environment:
  MAVEN_VERSION: 3.3.9
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%;
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
test_script:
  - mvn test
build_script:
  - mvn clean verify
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
```

I tested it on my fork and it works.

PS I added it on my pull request too
